export const CATEGORY = [
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "Data Engineer",
  "Data Analyst",
  "Business Analyst",
  "Product Manager",
  "Project Manager",
  "UI/UX Designer",
  "Graphic Designer",
  "Content Writer",
  "Digital Marketer",
  "Sales Manager",
  "HR Manager",
  "Finance Manager",
  "Operations Manager",
  "Blockchain Developer",
  "Cyber Security Engineer",
  "Cloud Engineer",
  "Game Developer",
  "Embedded Systems Engineer",
  "Robotics Engineer",
  "Quantitative Analyst",
  "Quantitative Developer",
  "Founder",
  "Investor",
  "Angel Investor",
  "Venture Capitalist",
  "HR",
];

export const SKILLS = [
  "React",
  "React Native",
  "Redux",
  "Node",
  "Express",
  "MongoDB",
  "Firebase",
  "GraphQL",
  "TypeScript",
  "JavaScript",
  "HTML",
  "CSS",
  "Python",
  "Django",
  "Flask",
  "SQL",
  "PostgreSQL",
  "MySQL",
  "Git",
  "GitHub",
  "GitLab",
  "Docker",
  "AWS",
  "GCP",
  "Azure",
  "Heroku",
  "Netlify",
  "Vercel",
  "Figma",
  "Adobe XD",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "Adobe After Effects",
  "Adobe Premiere Pro",
  "Adobe Lightroom",
  "Adobe InDesign",
  "Adobe Audition",
  "Adobe Animate",
  "Adobe Spark",
  "Adobe Spark AR",
  "Adobe Spark Video",
  "Adobe Spark Post",
  "Adobe Spark Page",
  "Java",
  "C++",
  "C",
  "C#",
  "R",
  "Rust",
  "Go",
  "Kotlin",
  "Swift",
  "Dart",
  "Flutter",
  "TensorFlow",
  "Solidity",
  "Web3.js",
  "Next.js",
  "Gatsby",
  "Vue",
  "Angular",
  "Svelte",
  "Nuxt",
  "Jest",
  "Mocha",
  "Chai",
  "Jasmine",
  "Solid.js",
  "Tailwind",
  "Bootstrap",
  "Material UI",
];

export const AVAILABLE_FOR = [
  "Full Time Roles",
  "Part Time Roles",
  "Freelance roles",
  "Internship Roles",
  "Contract Roles",
  // "Advicing",
  "Mentorship",
  "Networking",
  // "Open Source Contribution",
  // "Volunteering",
];

export const ACTIVITY_TAGS = [
  "Building web app",
  "Building mobile app",
  "Deployed website",
];

export const LOCATIONS = [
  "Agra",
  "Bengaluru",
  "Chennai",
  "Delhi",
  "Hyderabad",
  "Kolkata",
  "Mumbai",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Noida",
  "Gurgaon",
  "Chandigarh",
  "Indore",
  "Bhopal",
  "Patna",
  "Jodhpur",
  "Kanpur",
  "Nagpur",
  "Bhubaneswar",
];

export const LOOKING_FOR = [
  "Co-founder",
  "Investors",
  "Mentoring ",
  "Freelancer",
  "Intern",
  "Volunteer",
  "Open source contributor",
  "Advice",
  "Hackathon Partner",
  "Ui/Ux Designer",
  "Graphic Designer",
  "Content Writer",
  "Digital Marketer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "App Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
];

export const TAGS = [
  "ProjectShowcase",
  "BuildingInPublic",
  "Building ",
  "Introduction",
  "Idea",
  "100DaysOfCode",
  "100DaysOfDesign",
  "100DaysOfWriting",
  "Prototype",
  "MVP",
  "Blockchain",
  "Web3",
  "NFT",
  "DeFi",
  "DAO",
  "AI",
  "Startup",
  "OpenSource",
  "Hackathon",
  "Freelance",
  "Internship",
  "Fundraising",
  "Networking",
  "Brainstorming",
  "IdeaValidation",
  "Hiring",
  "Design",
  "Branding",
  "Marketing",
  "Sales",
  "ProductManagement",
  "Tech",
  "Finance",
  "Operations",
  "Legal",
];

export const FILTERED_CATEGORY = [
  {
    id: 1,
    num: 100,
    title: "People who want to",
    subTitle: "Network",
    slug: "networking",
    bgCol: "bg-secondary",
    txtCol: "text-dark border-dark",
  },
  {
    id: 2,
    num: 40,
    title: "People are open to",
    subTitle: "Mentoring",
    slug: "mentorship",
    bgCol: "bg-dark",
    txtCol: "text-white border-white",
  },
  {
    id: 4,
    num: 80,
    title: "People are available for",
    subTitle: "Freelancing",
    slug: "freelance",
    bgCol: "bg-primary",
    txtCol: "text-white border-white",
  },
  {
    id: 3,
    num: 50,
    title: "People are available for",
    subTitle: "Internship Roles",
    slug: "internship",
    bgCol: "bg-secondary",
    txtCol: "text-dark border-dark",
  },
];

export const CHAT_CONST = {
  CONNECT: "connect",
  DISCONNECT: "disconnect",
  CONNECT_ERROR: "connect_error",
  CONNECT_TIMEOUT: "connect_timeout",
  ERROR: "error",
  RECONNECT: "reconnect",
  RECONNECT_ATTEMPT: "reconnect_attempt",
  RECONNECT_FAILED: "reconnect_failed",
  RECONNECT_ERROR: "reconnect_error",
  RECONNECTING: "reconnecting",
  PING: "ping",
  PONG: "pong",
  CONNECTED: "CONNECTED",
  USER_TYPING: "USER_TYPING",
  STOP_TYPING: "STOP_TYPING",
  NEW_MESSAGE: "NEW_MESSAGE",
  MESSAGE_RECIEVED: "MESSAGE_RECIEVED",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  USER_LEFT_CHAT: "USER_LEFT",
  USER_JOINED_CHAT: "USER_JOINED",
  LEAVE_CHAT: "LEAVE_CHAT",
  SETUP: "SETUP",
  CHAT_FULL: "CHAT_FULL",

  /* NOTIFICATIONS */
  SEND_NOTIFICATION: "SEND_NOTIFICATION",
  NOTIFICATION_RECIEVED: "NOTIFICATION_RECIEVED",
};

// export const API_ENDPOINT_PROD = "https://api-test.piqr.in/";
export const API_ENDPOINT_PROD = "https://api.piqr.in/";
export const API_ENDPOINT_DEV = "http://localhost:6969";

export const NOTIFICATION_TYPES = {
  MESSAGE: "MESSAGE",
  LIKE: "LIKE",
  ENDORSE: "ENDORSE",
  FOLLOW: "FOLLOW",
  COMMENT: "COMMENT",
  MENTION: "MENTION",
  REPLY: "REPLY",
  UPVOTE: "UPVOTE",
};

export const SOCIAL_LINKS = [
  "twitter",
  "linkedin",
  "instagram",
  "medium",
  "website",
  "dribble",
  "github",
  "fueler",
  "youtube",
  "behance",
];

export const NOT_ALLOWED_PEOPLE = ["643e4c2f09a534cc9da1478a"];
